---
title: JPE Replication Report
date: today
number-sections: true
format:
  html: default
---

# Paper Identification

|  |   |
| ---  |  -------|
| ID  |  {{< var paper_id >}} |
| Author  |  {{< var author >}} |
| Title  |  {{< var title >}} |
| Iteration |  {{< var round >}} |

Some useful information up front:

- [JPE Data and Code Availability Policy](https://www.journals.uchicago.edu/journals/jpe/datapolicy)
- [Step by step guidance from Data Editor for Authors](https://jpedataeditor.github.io/) 
- [Template README](https://social-science-data-editors.github.io/template_README/)

# Summary

In assessing compliance with our [Data and Code Availability Policy](https://www.journals.uchicago.edu/journals/jpe/datapolicy), our reproducibility team has identified the following issues, which we ask you to address:

# General

- [X] Data Availability and Provenance Statements
  - [X] Statement about Rights - Part 1: Right to use the data (e.g. *did the authors lawfully obtain the data*)
  - [X] Statement about Rights - Part 2: Right to publish the data (e.g. *are human subjects involved and did permission been granted to publish their data?*)
  - [X] License for Data (optional, but recommended)
  - [X] Details on each Data Source
- [X] Dataset list
- [X] Computational requirements
  - [X] Software Requirements
  - [X] Controlled Randomness (as necessary)
  - [X] Memory, Runtime, and Storage Requirements
- [X] Description of programs/code
  - [X] License for Code (Optional, but recommended) 
  - [X] Details (as necessary)
- [X] List of tables and programs
- [X] References (Optional, but recommended) 


# High-level Description of Research Project

*This research project...*

- [X] uses observational data.
- [X] uses *confidential* observational data.
- [ ] uses data generated via experiment or trial by the authors (in field or lab).
  - [ ] For lab experiments: The code to implement the experimental protocol (z-Tree, o-Tree etc) is included in the package.
  - [ ] A PDF copy of IRB approval is contained in the package.
  - [ ] A PDF document outlining the design of the experiment, including information on the selection and eligibility of participants is included.
  - [ ] A PDF copy of the instructions given to participants in both original language and an English translation is included.
- [ ] uses data generated via survey by the authors (in field or online)
  - [ ] The programs used to administer the survey (e.g. qualtrics survey file) are included.
  - [ ] A PDF copy of IRB approval is contained in the package.
  - [ ] A PDF of the original questionaire(s) and information on the selection and eligibility of participants is included.
- [ ] is a simulation study: the data are generated by an algorithm.
- [ ] is a numerical illustration: no data are used but code is used to produce illustrative output (tables, figures)


# Data description

For any data that cannot be provided as part of the replication package, please provide the following information as part of the README.

> {REQUIRED}  Please specify how long the data will be preserved in the restricted-access location.

> {REQUIRED} Please provide affirmation of support for replication checks.
  - As per the [JPE policy](https://jpedataeditor.github.io/policy.html), "In cases where data cannot be published in an openly accessible trusted data repository like the JPE dataverse, authors who have requested an exemption to publish them at the time of first submission must commit to preserving the data and code for a period of no less than five years following the publication of the paper. They should also provide reasonable assistance to requests for clarification and replication."


> {REQUIRED} Please provide a codebook for the data.
  - The codebook should at a minimum describe the variables obtained from the data source, in a manner that will let others verify that they have obtained a substantially similar dataset if successfully obtaining access to the data.


## Data Sources

| file/name | public | private | DOI/URL | Access described | cited readme | cited paper |
| ---- | --- | --- | --- | --- | ---- | ---- |
| `data/raw/FEDFUNDS_Q.xls`; `data/raw/FEDFUNDS_Q.csv` (Federal funds rate, FRED/Federal Reserve) | Yes | No | [FRED Series FEDFUNDS](https://fred.stlouisfed.org/series/FEDFUNDS) | Yes (access date provided) | Yes | No |
| `data/raw/DGS1.csv` (1-year Treasury constant maturity rate, FRED/Federal Reserve) | Yes | No | [FRED Series DGS1](https://fred.stlouisfed.org/series/DGS1) | Yes (access date provided) | Yes | No |
| `data/raw/TB3MS.csv` (3-month Treasury bill rate, FRED/Federal Reserve) | Yes | No | [FRED Series TB3MS](https://fred.stlouisfed.org/series/TB3MS) | Yes (access date provided) | Yes | No |
| `data/raw/GDPDEF_Q.csv` (GDP deflator, FRED/BEA) | Yes | No | [FRED Series GDPDEF](https://fred.stlouisfed.org/series/GDPDEF) | Yes (access date provided) | Yes | No |
| `data/raw/GDPr_Q_BEA.xls`; `data/raw/GDPr_Q_BEA_Sheet0.csv`; `data/raw/GDPr_Q_BEA_Sheet1.csv` (BEA real GDP) | Yes | No | [BEA website](https://www.bea.gov/) | Yes (access date provided) | Yes | No |
| `data/raw/GVADEF_Q_BEA.xls`; `data/raw/GVADEF_Q_BEA_Sheet0.csv`; `data/raw/GVADEF_Q_BEA_Sheet1.csv` (BEA GVA/value-added deflator) | Yes | No | [BEA website](https://www.bea.gov/) | Yes (access date provided) | Yes | No |
| `data/raw/LPAgg_data/PCECC96.*`, `GPDIC1.*`, `GCEC1.*`, `DNDGRD3Q086SBEA.*`, `A006RD3Q086SBEA.*`, `A009RD3Q086SBEA.*`, `Y033RD3Q086SBEA.*` (aggregate consumption, investment, government spending, and deflators; FRED/BEA) | Yes | No | [FRED/BEA sources](https://doi.org/10.3886/E117644V1) | Yes (access date provided) | Yes | Luetticke (2021) article, but no data citation |
| `data/raw/FRB_Z1.csv` (Federal Reserve Financial Accounts / Flow of Funds Z.1) | Yes | No | [Federal Reserve Z.1](https://www.federalreserve.gov/releases/z1/) | Yes (access date provided) | Yes | No |
| `data/raw/bds2018.csv`; `data/raw/bds2018_fage.csv` (U.S. Census Bureau Business Dynamics Statistics, 2018 release) | Yes | No | [Census BDS data page](https://www.census.gov/programs-surveys/bds/data.html) | Yes (access date provided) | Yes | No |
| `data/raw/JK_data_fig4.csv` (Jarocinski-Karadi monetary policy shocks) | Yes | No | [replication data DOI](https://doi.org/10.3886/E231538V1) | Yes (access date provided) | Yes | Jarocinski and Karadi (2020) article, but no data citation |
| `data/raw/sffr_RR.csv` (Romer-Romer monetary policy shocks, robustness) | Yes | No | [Ramey replication zip](https://econweb.ucsd.edu/~vramey/research/Ramey_HOM_monetary.zip) | Yes (access date provided) | Yes | Romer and Romer (2004) and Ramey (2016), but no data citation |
| `proprietary-data-not-for-publication/raw/CS_data_raw.csv` (Compustat North America Quarterly) | No | Yes | - | Yes (institutional access required) | Yes | No |
| `proprietary-data-not-for-publication/raw/CRSP_data_raw.csv` (CRSP U.S. Stock Database) | No | Yes | - | Yes (institutional access required) | Yes | No |
| `proprietary-data-not-for-publication/raw/CCM_data_raw.csv` (CRSP/Compustat Merged links) | No | Yes | - | Yes (institutional access required) | Yes | No |
| `proprietary-data-not-for-publication/raw/Wscope_data_raw.xlsx` (Worldscope / Refinitiv Datastream incorporation and foundation dates) | No | Yes | - | Yes (institutional access required) | Yes | No |

# Requirements 

- [X] README is in TXT, MD, or PDF format
- [X] README is accessible at the root of the package (not inside a folder)
- [ ] Title conforms to guidance (starts with "Data and Code for: Title of Paper" or "Code for: Title of Paper", is properly capitalized)
- [X] Authors (with affiliations) are listed in the same order as on the paper

> {REQUIRED} Please review the title of the deposit as per our guidelines.

## Stated Requirements

- [X] Software Requirements specified as follows:
  - macOS Sequoia 15.4.1 (24E263)
  - Python 3.9.5
  - R 4.1.0
  - Julia 1.9.1
  - MATLAB, version 9.12.0.1956245 (R2022a) Update 2
- [X] Computational Requirements specified as follows:
  - 3.2 GHz 6-Core Intel Core i7 processor
  - 64 GB of RAM
  - Approximately 120 GB of available storage
- [X] Time Requirements specified as follows:
  - about 22 hours

- [ ] Requirements are complete.

# Analyzing Data and Code Files

{{< include generated/report-pii.md >}}

{{< include generated/report-file-paths.md >}}

{{< include generated/report-duplicates.md >}}

{{< include generated/report-zero-files.md >}}

{{< include generated/report-large-files.md >}}


## Code description

The replication contains a Main Python script Master_main.py calling the main Python, Julia, R and Matlab pipelines in two sections, Empirics and Model. In addition to this, package provides language-specific scripts to install required dependencies.


{{< include generated/report-cloc.md >}}


- [X] The replication package contains a "main" or "master" file(s) which calls all other auxiliary programs.

## Computing Environment of the Replicator

- Nuvolos Cloud, with standard configuration 16 cores and 64GB RAM, scaled up to 120 cores and 448GB of RAM to run model in Julia. Storage quota increased up to 150GB to accommodate model output. To ease comparisons with authors' setup, we report here also the list of dependencies used, which were installed following the README instructions.

- Python 3.9.23 using
  - pandas==1.3.1
  - numpy==1.24.4
  - scipy==1.8.1
  - openpyxl==3.1.5
  - xlrd==2.0.2
  - pytz==2026.2
  - python-dateutil==2.9.0post0
- Julia 1.9.1
  - AverageShiftedHistograms==0.8.9
  - Binscatters==0.4.0
  - CSV==0.10.14
  - CompEcon==0.4.0
  - DataFrames==1.5.0
  - Distributions==0.25.45
  - GLM==1.9.0
  - Interpolations==0.15.1
  - JLD==0.13.5
  - LaTeXStrings==1.3.1
  - Plots==1.40.8
  - QuantEcon==0.16.6
  - Roots==2.2.1
- R 4.1.2
  - plm==2.4-1
  - plyr==1.8.6
  - lmtest==0.9-38
  - stargazer==5.2.2
  - lfe==2.8-6
  - moments==0.14
  - xtable==1.8.4
  - fixest==0.10.1
- Matlab R2022a



# Replication

- Downloaded code and data from dropbox and cloned Git repo.
- Instantiated Julia, Python and R dependencies following Readme. Our cloud machine makes it complex to run all within Python, as cross-application interaction is limited. Therefore, replicator proceeded running master script tasks separately by language, following the script's order.
- Adjustment before running run_python(PROJECT_ROOT / "code" / "Python" / "FOFA_analysis_code.py") for missing dependencies pytz and dateutil. Installed via conda install pytz and conda install python-dateutil. Ran again. Authors might want to add these two package dependencies to their script and README.
- Running "JPE_REPLICATION_FINAL/code/Julia/Julia_model_code/Master_model_work.jl" required more resources than described by README. We ran out of RAM memory with 64 and 128 GB on a Linux-based system. Also, storage needed to be increased above 120 GB. 
- Ran the rest of the code successfully.

# Findings {#sec-findings}

## Missing Requirements

- [X] Software Requirements 
  - [ ] Python packages
    - pytz
    - dateutil

> [REQUIRED] Please amend README to contain complete requirements. 

Additionally, authors are invited to doublecheck RAM and storage requirements, as running "JPE_REPLICATION_FINAL/code/Julia/Julia_model_code/Master_model_work.jl" required more resources than described by README. We ran out of RAM memory with 64 and 128 GB on a Linux-based system. Also, allocated storage needed to be increased to 150 GB. 

## Data Preparation Code

Data Preparation Code ran without errors.

## Tables and Figures

Replication successfully generated all tables and figures in the paper. All replicated output matched latest draft of the paper.

| Figure/Table # | Program | Line Number | Reproduced |
| --- | --- | --- | --- |
| Figure 1 (Fig1a, Fig1b) | code/R/Micro_reg_code.r | 404, 415, 425 | Yes |
| Figure 2 (Fig2a-Fig2c) | code/R/Micro_eventstudy_plottr.r | 68 | Yes |
| Figure 3 (Fig3a, Fig3b) | code/R/Micro_reg_code.r | 1387 | Yes |
| Figure 4 (Fig4a, Fig4b) | code/Julia/Julia_model_code/Master_model_work.jl | 280, 431 | Yes |
| Figure 5 | code/Julia/Julia_model_code/Master_model_work.jl | 579 | Yes |
| Figure 6 | code/Julia/Julia_model_code/auxiliary_model_functions.jl | 2487 | Yes |
| Figure 7 (Fig7a, Fig7b) | code/Julia/Julia_model_code/Master_model_work.jl | 1104, 1127 | Yes |
| Figure 8 (Fig8a, Fig8b) | code/Julia/Julia_model_code/Master_model_work.jl | 1161, 1171 | Yes |
| Table 1 | code/R/Micro_reg_code.r | 746 | Yes |
| Table 2 | code/Julia/Julia_model_code/Master_model_work.jl | 831 | Yes |
| Figure A.1 | code/R/Micro_reg_code.r | 404 | Yes |
| Table A.1 | code/R/Micro_reg_code.r | 1005 | Yes |
| Table A.2 | code/R/Micro_reg_code.r | 517 | Yes |
| Table A.3 | code/R/Micro_reg_code.r | 612 | Yes |
| Table A.4 | code/R/Micro_reg_code.r | 679 | Yes |
| Figure A.2 (FigA2a-FigA2c) | code/R/Micro_eventstudy_plottr.r | 98 | Yes |
| Figure A.3 (FigA3a-FigA3c) | code/R/Micro_eventstudy_plottr.r | 98 | Yes |
| Figure A.4 (FigA4a-FigA4c) | code/R/Micro_eventstudy_plottr.r | 98 | Yes |
| Figure A.5 (FigA5a, FigA5b) | code/R/Micro_reg_code.r | 1387, 1922 | Yes |
| Figure A.6 (FigA6a-FigA6d) | code/R/Micro_reg_code.r | 1387, 1922 | Yes |
| Figure A.7 (FigA7a, FigA7b) | code/R/Micro_reg_code.r | 1387 | Yes |
| Figure A.8 (FigA8a, FigA8b) | code/R/Micro_reg_code.r | 1387 | Yes |
| Figure A.9 (FigA9a, FigA9b) | code/R/Micro_reg_code.r | 1387 | Yes |
| Figure A.10 (FigA10a, FigA10b) | code/R/Micro_reg_code.r | 1405 | Yes |
| Figure A.11 (FigA11a, FigA11b) | code/R/Micro_reg_code.r | 1387 | Yes |
| Figure A.12 (FigA12a, FigA12b) | code/R/Micro_reg_code.r | 1387, 1756 | Yes |
| Figure A.13 (FigA13a, FigA13b) | code/R/Micro_reg_code.r | 1756 | Yes |
| Figure A.14 (FigA14a, FigA14b) | code/R/Micro_reg_code.r | 2212, 2237 | Yes |
| Table A.5 | code/Python/FOFA_analysis_code.py | 107 | Yes |
| Figure A.15 (FigA15a-FigA15d) | code/MATLAB/LPAgg_main.m | 183, 205, 227, 250 | Yes |
| Table B.1 (manual table from components) | code/Julia/Julia_empirics_code/BDS_analysis_code.jl; code/R/Micro_reg_code.r; code/Julia/Julia_model_code/Master_model_work.jl | 40; 218; 204 | Yes |
| Table B.2 | code/Python/Generate_TabB2.py | 15, 60 | Yes |
| Table B.3 | code/R/Micro_model_reg_code.r | 205 | Yes |
| Table B.4 | code/R/Micro_model_reg_code.r | 273 | Yes |
| Table B.5 (manual table from component) | code/Julia/Julia_model_code/calib_functions.jl | 392 | Yes |
| Figure B.1 | code/Julia/Julia_model_code/calib_functions.jl | 338 | Yes |
| Figure B.2 | code/Julia/Julia_model_code/auxiliary_model_functions.jl | 2514 | Yes |
| Figure B.3 (FigB3a, FigB3b) | code/Julia/Julia_model_code/auxiliary_model_functions.jl | 2585, 2648 | Yes |
| Figure B.4 | code/Julia/Julia_model_code/auxiliary_model_functions.jl | 2526 | Yes |
| Figure B.5 | code/Julia/Julia_model_code/Master_model_work.jl | 1088 | Yes |
| Figure B.6 | code/Julia/Julia_model_code/Master_model_work.jl | 690 | Yes |
| Figure B.7 | code/Julia/Julia_model_code/Master_model_work.jl | 738 | Yes |
| Figure B.8 | code/Julia/Julia_model_code/Master_model_work.jl | 1146 | Yes |
| Figure B.9 | code/Julia/Julia_model_code/Master_model_work.jl | 1330 | Yes |
| Figure B.10 | code/Julia/Julia_model_code/Master_model_work.jl | 612 | Yes |
| Figure B.11 (FigB11a, FigB11b) | code/Julia/Julia_model_code/auxiliary_model_functions.jl; code/Julia/Julia_model_code/Master_model_work.jl | 2492; 1245 | Yes |
| Figure B.12 | code/Julia/Julia_model_code/Master_model_work.jl | 1457 | Yes |
| Figure B.13 (FigB13a, FigB13b) | code/Julia/Julia_model_code/auxiliary_model_functions.jl; code/Julia/Julia_model_code/Master_model_work.jl | 2495; 1574 | Yes |
| Figure B.14 (FigB14a, FigB14b) | code/Julia/Julia_model_code/Master_model_work.jl | 1474, 1590 | Yes |

## In-Text Numbers

- [ ] In-text numbers not verified.

- [ ] There are no in-text numbers, or all in-text numbers stem from tables and figures.

- [ ] There are in-text numbers, but they are not identified in the code

- [X] There are in-text numbers, and the identified in-text numbers were verified against the auxiliary output files.

All in-text numbers detected were reproduced by the replication package. Replicated in-text numbers match the ones reported in the paper. 

| In-text numbers | Program | Line Number | Reproduced |
| --- | --- | --- | --- |
| Footnote 3 | code/R/Micro_reg_code.r | 258, 313 | Yes |
| Footnote 15 | code/R/Micro_reg_code.r | 308 | Yes |
| Footnote 46 | code/Julia/Julia_model_code/Master_model_work.jl | 215 | Yes |
| Section 4.2 text | code/Julia/Julia_model_code/Master_model_work.jl | 288 | Yes |
| Section 5.1 text | code/Julia/Julia_model_code/Master_model_work.jl | 671 | Yes |
| Section 5.2 text | code/Julia/Julia_model_code/Master_model_work.jl | 1188, 1212, 1332 | Yes |
| Footnote 57 | code/Julia/Julia_model_code/Master_model_work.jl | 1220 | Yes |
| Appendix A.2 text | code/R/Micro_reg_code.r | 520 | Yes |
| Footnote 61 | code/R/Micro_reg_code.r | 791 | Yes |
| Footnote 74 | code/R/Micro_reg_code.r | 327 | Yes |
| Appendix B.5.3 text | code/Julia/Julia_model_code/Master_model_work.jl | 372 | Yes |
| Footnote 87 | code/Julia/Julia_model_code/calib_functions.jl | 345 | Yes |
| Appendix B.10.1 text | code/Python/FOFA_analysis_code.py; code/Python/TB3_analysis_code.py | 111; 29 | Yes |
| Appendix B.11.1 text | code/Julia/Julia_model_code/Master_model_work.jl | 495 | Yes |
| Appendix B.11.2 text | code/Julia/Julia_model_code/Master_model_work.jl | 1616 | Yes |

# Classification

- [X] full reproduction
- [ ] full reproduction with minor issues
- [ ] partial reproduction (see above)
- [ ] not able to reproduce most or all of the results (reasons see above)

## Reason for incomplete reproducibility

- [X] None.
- [ ] `Discrepancy in output` (either figures or numbers in tables or text differ)
- [ ] `Bugs in code` that were fixable by the replicator (but should be fixed in the final deposit)
- [ ] `Code missing`, in particular if it prevented the replicator from completing the reproducibility check
  - [ ] `Data preparation code missing` should be checked if the code missing seems to be data preparation code
- [ ] `Code not functional` is more severe than a simple bug: it prevented the replicator from completing the reproducibility check
- [ ] `Software not available to replicator` may happen for a variety of reasons, but in particular (a) when the software is commercial, and the replicator does not have access to a licensed copy, or (b) the software is open-source, but a specific version required to conduct the reproducibility check is not available.
- [ ] `Insufficient time available to replicator` is applicable when (a) running the code would take weeks or more (b) running the code might take less time if sufficient compute resources were to be brought to bear, but no such resources can be accessed in a timely fashion (c) the replication package is very complex, and following all (manual and scripted) steps would take too long.
- [ ] `Data missing` is marked when data *should* be available, but was erroneously not provided, or is not accessible via the procedures described in the replication package
- [ ] `Data not available` is marked when data requires additional access steps, for instance purchase or application procedure. 
- [ ] `Missing README` is marked if there is no README to guide the replicator, or the README is not in compliance with JPE requirements
